version: '3.7'
services:
  app:
    container_name: godubi-production
    image: godubi/backend-production
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - '8085:8085'
