version: '3.7'
services:
  app:
    container_name: godubi
    image: mrb-direct/backend
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      target: development
    command: yarn start:dev app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '8085:8085'
